import { Template } from '@/types';

export const assessmentFormats = {
  knowledge: [
    { value: 'multiple_choice', label: 'Multiple Choice', description: 'Test recall with options' },
    { value: 'true_false', label: 'True/False', description: 'Binary choice questions' },
    { value: 'matching', label: 'Matching', description: 'Connect related items' },
    { value: 'short_answer', label: 'Short Answer', description: 'Brief written responses' },
  ],
  skills: [
    { value: 'case_study', label: 'Case Study', description: 'Analyze real scenarios' },
    { value: 'practical', label: 'Practical Exercise', description: 'Hands-on application' },
    { value: 'simulation', label: 'Digital Simulation', description: 'Virtual practice environment' },
    { value: 'simple_project', label: 'Simple Project', description: 'Basic implementation task' },
  ],
  abilities: [
    { value: 'complex_project', label: 'Complex Project', description: 'Multi-phase implementation' },
    { value: 'problem_solving', label: 'Advanced Problem-Solving', description: 'Complex challenges' },
    { value: 'presentation', label: 'Oral Presentation', description: 'Verbal demonstration' },
    { value: 'collaborative', label: 'Collaborative Assessment', description: 'Group-based evaluation' },
  ],
} as const;

export const assessmentLevels = {
  1: { label: 'Unsatisfactory', description: 'Essential criteria not met' },
  2: { label: 'Satisfactory', description: 'Minimum requirements met' },
  3: { label: 'Very Satisfactory', description: 'Exceeds minimum expectations' },
  4: { label: 'Excellent', description: 'Exemplary mastery of all criteria' },
} as const;

export const knowledgeTypes = {
  knowledge: {
    levels: ['remembering', 'understanding'],
    label: 'Knowledge',
    description: 'Knowledge and comprehension',
    formats: assessmentFormats.knowledge,
    allowsPerformanceThreshold: false,
  },
  skills: {
    levels: ['applying', 'analyzing'],
    label: 'Skills',
    description: 'Application and analysis',
    formats: assessmentFormats.skills,
    allowsPerformanceThreshold: true,
  },
  abilities: {
    levels: ['evaluating', 'creating'],
    label: 'Competency',
    description: 'Evaluation and creation',
    formats: assessmentFormats.abilities,
    allowsPerformanceThreshold: true,
  },
} as const;

export const templates: Template[] = [
  {
    id: 'creative-skills',
    name: 'Creative Skills Development',
    description: 'Develop creative thinking and problem-solving abilities',
    totalHours: 12,
    color: 'hsl(280, 85%, 75%)',
    objectives: [
      {
        level: 'creating',
        verb: 'Create',
        dimension: 'processes',
        dimensionText: 'original solutions to complex problems using creative thinking techniques',
        parentId: null,
        workloadHours: 6,
        subObjectives: [
          {
            level: 'analyzing',
            verb: 'Analyze',
            dimension: 'concepts',
            dimensionText: 'problem components and identify key elements for creative solutions',
            parentId: '1',
            workloadHours: 2,
          },
          {
            level: 'applying',
            verb: 'Apply',
            dimension: 'procedures',
            dimensionText: 'divergent thinking techniques to generate multiple solution approaches',
            parentId: '1',
            workloadHours: 2,
          },
          {
            level: 'evaluating',
            verb: 'Evaluate',
            dimension: 'metacognitive',
            dimensionText: 'the effectiveness and feasibility of proposed creative solutions',
            parentId: '1',
            workloadHours: 2,
          },
        ],
      },
      {
        level: 'evaluating',
        verb: 'Evaluate',
        dimension: 'metacognitive',
        dimensionText: 'the effectiveness of different creative approaches and methodologies',
        parentId: null,
        workloadHours: 6,
        subObjectives: [
          {
            level: 'understanding',
            verb: 'Compare',
            dimension: 'concepts',
            dimensionText: 'various creative thinking methodologies and their applications',
            parentId: '2',
            workloadHours: 2,
          },
          {
            level: 'applying',
            verb: 'Implement',
            dimension: 'procedures',
            dimensionText: 'selected creative methods in different problem-solving scenarios',
            parentId: '2',
            workloadHours: 2,
          },
          {
            level: 'analyzing',
            verb: 'Examine',
            dimension: 'principles',
            dimensionText: 'the outcomes and effectiveness of each methodology',
            parentId: '2',
            workloadHours: 2,
          },
        ],
      },
    ],
  },
  {
    id: 'communication',
    name: 'Communication and Public Speaking',
    description: 'Master effective communication and presentation skills',
    totalHours: 18,
    color: 'hsl(200, 85%, 75%)',
    objectives: [
      {
        level: 'applying',
        verb: 'Deliver',
        dimension: 'procedures',
        dimensionText: 'engaging presentations using proper public speaking techniques',
        parentId: null,
        workloadHours: 6,
        subObjectives: [
          {
            level: 'understanding',
            verb: 'Structure',
            dimension: 'principles',
            dimensionText: 'presentations using effective organizational patterns',
            parentId: '1',
            workloadHours: 2,
          },
          {
            level: 'applying',
            verb: 'Demonstrate',
            dimension: 'procedures',
            dimensionText: 'proper vocal techniques and body language',
            parentId: '1',
            workloadHours: 2,
          },
          {
            level: 'evaluating',
            verb: 'Assess',
            dimension: 'metacognitive',
            dimensionText: 'personal delivery style and areas for improvement',
            parentId: '1',
            workloadHours: 2,
          },
        ],
      },
      {
        level: 'analyzing',
        verb: 'Analyze',
        dimension: 'principles',
        dimensionText: 'audience engagement and adapt communication strategies accordingly',
        parentId: null,
        workloadHours: 6,
        subObjectives: [
          {
            level: 'understanding',
            verb: 'Identify',
            dimension: 'concepts',
            dimensionText: 'different audience types and their characteristics',
            parentId: '2',
            workloadHours: 2,
          },
          {
            level: 'applying',
            verb: 'Modify',
            dimension: 'procedures',
            dimensionText: 'communication approach based on audience feedback',
            parentId: '2',
            workloadHours: 2,
          },
          {
            level: 'evaluating',
            verb: 'Measure',
            dimension: 'metacognitive',
            dimensionText: 'the effectiveness of different engagement strategies',
            parentId: '2',
            workloadHours: 2,
          },
        ],
      },
      {
        level: 'creating',
        verb: 'Develop',
        dimension: 'metacognitive',
        dimensionText: 'personalized communication strategies for different contexts',
        parentId: null,
        workloadHours: 6,
        subObjectives: [
          {
            level: 'analyzing',
            verb: 'Research',
            dimension: 'facts',
            dimensionText: 'communication requirements for different contexts',
            parentId: '3',
            workloadHours: 2,
          },
          {
            level: 'creating',
            verb: 'Design',
            dimension: 'processes',
            dimensionText: 'tailored communication approaches for each context',
            parentId: '3',
            workloadHours: 2,
          },
          {
            level: 'evaluating',
            verb: 'Review',
            dimension: 'metacognitive',
            dimensionText: 'the success of implemented communication strategies',
            parentId: '3',
            workloadHours: 2,
          },
        ],
      },
    ],
  },
  {
    id: 'memory-focus',
    name: 'Memory and Focus Enhancement',
    description: 'Improve memory retention and concentration abilities',
    totalHours: 6,
    color: 'hsl(150, 85%, 75%)',
    objectives: [
      {
        level: 'applying',
        verb: 'Apply',
        dimension: 'procedures',
        dimensionText: 'advanced memory techniques in practical learning situations',
        parentId: null,
        workloadHours: 6,
        subObjectives: [
          {
            level: 'understanding',
            verb: 'Explain',
            dimension: 'concepts',
            dimensionText: 'the principles behind effective memory techniques',
            parentId: '1',
            workloadHours: 2,
          },
          {
            level: 'applying',
            verb: 'Practice',
            dimension: 'procedures',
            dimensionText: 'concentration exercises and memory patterns',
            parentId: '1',
            workloadHours: 2,
          },
          {
            level: 'evaluating',
            verb: 'Monitor',
            dimension: 'metacognitive',
            dimensionText: 'personal progress in memory retention and focus',
            parentId: '1',
            workloadHours: 2,
          },
        ],
      },
    ],
  },
];